BIN = hellot
CC = g++
FLAGS = -Wall -pedantic
INC = -I ../common/include
SYS_LIB = -lXrandr -lpthread -lm -lglfw -lGLU -lGL -lGLEW
SRC = maths_funcs.cpp gl_utils.c main.c

all:
	${CC} ${FLAGS} -o ${BIN} ${SRC} ${SYS_LIB}


